{
 "title": "COVID-19 / Coronavirus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "countries", "label": "countries", "query": "*.*.Covid Data.*" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Serious/Critical Cases",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Covid Data" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAliasByRegex",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ]
       },
       "params": [ "\\[.*\\]" ],
       "text": "setAliasByRegex(\\[.*\\])"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/$countries - Serious/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 24, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "application": { "filter": "Covid Data" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAliasByRegex",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ]
       },
       "params": [ "\\[.+\\]" ],
       "text": "setAliasByRegex(\\[.+\\])"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/$countries - TotalDeaths/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "New Cases",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "application": { "filter": "Covid Data" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/$countries - NewCases/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cases (per million of inhabitants)",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "application": { "filter": "Covid Data" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAliasByRegex",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ]
       },
       "params": [ "\\[.+\\]" ],
       "text": "setAliasByRegex(\\[.+\\])"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "/$countries - Cases per Million habitants/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Active Cases",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "application": { "filter": "Covid Data" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [ "asc" ],
        "name": "sortSeries",
        "params": [
         {
          "name": "direction",
          "options": [
           "asc",
           "desc"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "desc" ],
       "text": "sortSeries(desc)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAliasByRegex",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ]
       },
       "params": [ "\\[.+\\]" ],
       "text": "setAliasByRegex(\\[.+\\])"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/$countries - ActiveCases/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of Recoveries",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Covid Data" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [ "asc" ],
        "name": "sortSeries",
        "params": [
         {
          "name": "direction",
          "options": [
           "asc",
           "desc"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "desc" ],
       "text": "sortSeries(desc)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAliasByRegex",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ]
       },
       "params": [ "\\[.+\\]" ],
       "text": "setAliasByRegex(\\[.+\\])"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/$countries - TotalRecovered/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Cases",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "application": { "filter": "Covid Data" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [ "asc" ],
        "name": "sortSeries",
        "params": [
         {
          "name": "direction",
          "options": [
           "asc",
           "desc"
          ],
          "type": "string"
         }
        ]
       },
       "params": [ "desc" ],
       "text": "sortSeries(desc)"
      },
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAliasByRegex",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ]
       },
       "params": [ "\\[.*\\]" ],
       "text": "setAliasByRegex(\\[.*\\])"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/$countries - TotalCases/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "COVID9 Info by $countries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "countries" },
  {
   "title": "Active Cases",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 27 },
   "targets": [
    {
     "application": { "filter": "Covid Data" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/$countries - ActiveCases/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Serious/Critical",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 27 },
   "targets": [
    {
     "application": { "filter": "Covid Data" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/$countries - Serious/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Casualities",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 27 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "application": { "filter": "Covid Data" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/$countries - TotalDeaths/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Covid Data" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/$countries - TotalRecovered/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}